# Site settings
title: "Saeed Poorjandaghi|Embedded System Engineer"
description: "Saeed Poorjandaghi Portfolio"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Saeed Poorjandaghi"
resume_title:                   "Embedded System Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "saeed.poorjandaghi@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+98)-937-982-0865"
resume_contact_address:         "No. 8, Goharshad St., Nofel Loshato St., Tehran, Iran"

resume_header_contact_info:     "No. 8, Goharshad St., Nofel Loshato St., Tehran, Iran• (+98)-937-982-0865 • saeed.poorjandaghi@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p align=justify>Before all else, I love writing embedded code. From the day on which I wrote my first assembly program on an 8051 microcontroller and manipulating it to control the speed of a DC motor, I've been obsessed with dealing with little abstraction from computer's instruction set. Then I discover electronics and the power of digital and analog circuits to make things that really work and the robotics was a natural fit so I build my first robot from scratch.       Robotics is a never-ending puzzle that I am passionately engaged in solving.<br><br>
My first volunteer experience was for Parsian small size soccer robot team, I was given the opportunity to develop embedded electronic systems for the soccer robots. My first part-time job involved designing electronics and developing embedded firmware for laboratory equipment. Then a full-time position is offered and I have been happily expanding my role as an embedded system team lead ever since to design and develop pick & place robots for manufacturing lines as well as embedded industrial electronic devices like industrial drivers, signal isolators and transmitters.<br><br>
I'm a hands-on manager and actively involved in day-to-day tasks. It gives me access to more ideas from the customers as well as my team members. Even when I leave the office, I tend to continue developing at the house. I believe that physical exercise truely feeds the brain and tennis is my passion and I find a beautiful crossover between my work and my sport. Most recently I've been working with some well-known robotics companies as a freelancer and I'm always interested to accept challenges. Reach out below to connect!
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/1saeed"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/1saeid"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
